# Generated by Django 5.1 on 2026-02-19 18:44

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('telefone', models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
